#!/bin/Rscript
sum_ <- 0

# 过滤掉统计行（以__开头的行）
valid_genes <- row.names(count)[!grepl("^__", row.names(count))]

for(i in valid_genes){
    count_ = count[i, "count"]
    exon  = gene_len[i, "length"]
    value = count_ / exon
    
    if(is.na(value)){
        print(paste(i, " is error! please check"))
    }else{
        sum_ = sum_ + value
    }
}

TPM <- numeric(nrow(count))

for(i in 1:nrow(count)){
    count_ = count[i, "count"]
    exon = gene_len[i, "length"]
    TPM[i] = (10 ^ 6 * count_ / exon) / sum_
}

count["RPKM"] <- RPKM
count["TPM"] <- TPM    
           
write.table(count, "123.normalize.count", col.names = TRUE, row.names = TRUE, sep="\t", quote = FALSE)