#!/bin/Rscript
# 设置到rat目录
setwd("~/project/rat")

# 使用相对路径
gene_len_file <- "annotation/rn6_gene_len.tsv"
count_file <- "output/HTseq/samples.count"

gene_len <- read.table(gene_len_file, header = FALSE, row.name = 1)
colnames(gene_len) <- c("length")

count <- read.table(count_file, header = FALSE, row.name = 1)
colnames(count) <- c("count" )
# all read number
all_count <- sum(count$count)

RPKM <- numeric(nrow(count))

for(i in 1:nrow(count)){
    count_val <- count[i, "count"]
    exon_kb <- gene_len[i, "length"] / 1000
    RPKM[i] <- (10^6 * count_val) / (exon_kb * all_count)
}